// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Application is the golang structure of table application for DAO operations like Where/Data.
type Application struct {
	g.Meta      `orm:"table:application, do:true"`
	Id          interface{} //
	Name        interface{} // 应用名称
	RedirectUrl interface{} // 应用地址
	AppId       interface{} // 应用ID
	AppSecret   interface{} // 应用密钥
	CreateTime  *gtime.Time // 创建时间
	UpdateTime  *gtime.Time // 更新时间
	DeleteTime  *gtime.Time // 删除时间
}
