// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} //
	Name       interface{} // 用户名
	Phone      interface{} // 手机号
	Email      interface{} // 邮箱
	Password   interface{} // 密码
	Code       interface{} // 短信验证码
	CodeTime   *gtime.Time // 验证码发送时间
	Appids     interface{} // 用户关联的应用
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 修改时间
	DeleteTime *gtime.Time // 删除时间
}
