server:
  address:     ":8369"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# jwtToken
jwt:
  salt: "Jk3r8NzoX2Pb6WQu"
  prefix: "ThinkSSO:"
  signe: "ThinkSSO-SIGNE"
  exp: 30
  excludePaths:
    - "/api/v1/login/email"
    - "/api/v1/login/phone"
    - "/api/v1/login/code"

# 数据库
database:
  logger:
    level:   "all"
    stdout:  true
    Path: "resource/log/sql"

  default:
    link:   "mysql:think-sso:dcGLEpj5JZReztBw@tcp(123.56.82.75:3306)/think-sso?charset=utf8mb4&parseTime=true&loc=Local"
    debug:  true
    charset: "utf8mb4" #数据库编码
    dryRun: false #空跑
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: "30s" #(单位秒)连接对象可重复使用的时间长度
    createdAt: "create_time"
    updatedAt: "update_time"
    deletedAt: "delete_time"

# Redis
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db:      1



