// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"think-sso/internal/dao/internal"
)

// internalApplicationDao is internal type for wrapping internal DAO implements.
type internalApplicationDao = *internal.ApplicationDao

// applicationDao is the data access object for table application.
// You can define custom methods on it to extend its functionality as you wish.
type applicationDao struct {
	internalApplicationDao
}

var (
	// Application is globally public accessible object for table application operations.
	Application = applicationDao{
		internal.NewApplicationDao(),
	}
)

// Fill with you ideas below.
