// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int         `json:"id"         description:""`
	Name       string      `json:"name"       description:"用户名"`
	Avatar     string      `json:"avatar"     description:"头像"`
	Phone      string      `json:"phone"      description:"手机号"`
	Email      string      `json:"email"      description:"邮箱"`
	Password   string      `json:"password"   description:"密码"`
	Code       int         `json:"code"       description:"短信验证码"`
	CodeTime   *gtime.Time `json:"codeTime"   description:"验证码发送时间"`
	AppIds     string      `json:"appIds"     description:"用户关联的应用"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"修改时间"`
	DeleteTime *gtime.Time `json:"deleteTime" description:"删除时间"`
}
