// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	v1 "think-sso/api/v1"
)

type (
	IApplication interface {
		HasApp(ctx context.Context, req *v1.CheckAuthReq) (err error)
	}
)

var (
	localApplication IApplication
)

func Application() IApplication {
	if localApplication == nil {
		panic("implement not found for interface IApplication, forgot register?")
	}
	return localApplication
}

func RegisterApplication(i IApplication) {
	localApplication = i
}
