// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IApplication interface {
		HasApp(ctx context.Context, AppId string, AppSecret string) (err error)
	}
)

var (
	localApplication IApplication
)

func Application() IApplication {
	if localApplication == nil {
		panic("implement not found for interface IApplication, forgot register?")
	}
	return localApplication
}

func RegisterApplication(i IApplication) {
	localApplication = i
}
