// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"think-sso/internal/model"
)

type (
	IToken interface {
		CreateToken(ctx context.Context, user *model.User) (err error)
		ParseJwt(ctx context.Context, token string) (*model.JwtUser, error)
		CheckToken(ctx context.Context, token string) (err error)
		RemoveToken(ctx context.Context, token string) (err error)
	}
)

var (
	localToken IToken
)

func Token() IToken {
	if localToken == nil {
		panic("implement not found for interface IToken, forgot register?")
	}
	return localToken
}

func RegisterToken(i IToken) {
	localToken = i
}
