// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	v1 "think-sso/api/v1"
)

type (
	IToken interface {
		CreateToken(ctx context.Context, user *v1.LoginRes) (encryptToken string, err error)
		ValidateToken(ctx context.Context, token string) (err error)
	}
)

var (
	localToken IToken
)

func Token() IToken {
	if localToken == nil {
		panic("implement not found for interface IToken, forgot register?")
	}
	return localToken
}

func RegisterToken(i IToken) {
	localToken = i
}
