// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	v1 "think-sso/api/v1"
	"think-sso/internal/model"
	"think-sso/internal/model/entity"
)

type (
	IUser interface {
		GetUserByEmailPassword(ctx context.Context, req *v1.EmailLoginReq) (res *entity.User, err error)
		GetUserList(ctx context.Context, req *v1.UserListReq) (total int, userList []*model.User, err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
